name: Android CI

on:
  push:
    branches:
      - "development"
    tags:
      - '1.1.0-SNAPSHOT'

jobs:
  build:
    name: Build and update release jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Update release jar
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        overwrite: true
        release_tag_name: 1.1.0-SNAPSHOT
        file: "app/build/libs/sdk-boost-1.1.0-SNAPSHOT.jar"
