name: Android CI

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    name: Build jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: d1ceward/draft-assets-release-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            app/build/libs/sdk-boost-1.0.0-SNAPSHOT.jar
            app/build/libs/app-sources.jar
